.github/workflows/ci.yml, .github/workflows/updpyver.yml
transifex-python doesn't support Python 3.12 yet, failing on pip install. See https://github.com/transifex/transifex-python/issues/106. See also these workflow runs of [updpyver.yml](https://github.com/rffontenelle/python-docs-tx-translations/actions/runs/6667718773/job/18121717863) and [ci.yml](https://github.com/rffontenelle/python-docs-tx-translations/actions/runs/6668346770/job/18123725648).
=> Pin Python 3.11 in GitHub Actions

.github/workflows/ci.yml
This is required to generate correct .tx/config and to push only non-obsolete resource for translation
Fixes #50
=> Remove POT files and .tx/config before regenerating again

scripts/lock-translations.py
From Actions log
```
> Run python3 scripts/lock-translations.py cpython/Doc/locales/.tx/config python-newest
/home/runner/work/python-docs-tx-translations/python-docs-tx-translations/scripts/lock-translations.py:28: SyntaxWarning: invalid escape sequence '\w'
project in re.search('p:python-[\w]+:', config.sections()[1]).group(0)
Using TX Config Path: cpython/Doc/locales/.tx/config
Using project: python-newest
Successfully retrieved local resources!
All resources are locked or in use!
```
=> Remove square brackets of regexp in lock-translations.py

.github/workflows/ci.yml
Fix cpython issue 122629, applying the PR 122653
This PR is mostly for me to trigger the CI workflow manually from this specific branch without having to merge the patch into main, as I the linked backport will probably me merged into cpython soon
=> Fix auditing events missing reST markups

.github/workflows/ci.yml
Running Sphinx's *gettext* builder via sphinx-build bypasses CPython's Makefile blurb instructions which compile all NEWS files into a Changelog file. By using the Makefile to run the *gettext* builder, we enable whatsnew/changelog translation.
Closes #101
=> Use make to run gettext sphinx builder

README.rst, docs/bumping-release.rst, docs/conf.py, docs/index.rst, docs/placeholders.rst, scripts/remove-msgid.sh
This is to fit into [python-docs-translations](https://github.com/python-docs-translations) organization
See #34 
----
📚 Documentation preview 📚: https://python-docs-tx-translations--114.org.readthedocs.build/en/114/
=> Rename project to transifex-automations

README.rst
All of the readme content is now in the Docs index so there is no need to keep two copies.
=> Link to docs in README

docs/new-translators.rst
A few little typo's and made it a bit more *strict*.
----
📚 Documentation preview 📚: https://python-docs-transifex-automation--122.org.readthedocs.build/en/122/
=> Updates to new-translators.rst

docs/conf.py
Not sure on what exactly it should be. The current (automatic) one is:
> Python Docs Transifex Automation documentation 
----
📚 Documentation preview 📚: https://python-docs-transifex-automation--127.org.readthedocs.build/en/127/
=> Add html_title to conf

docs/commands.rst, docs/new-translators.rst
Also "fix" codeblocks, unfortunately google did not provide a better solution.
----
📚 Documentation preview 📚: https://python-docs-transifex-automation--132.org.readthedocs.build/en/132/
=> Expand section on no existing project

docs/conf.py
repository slug was renamed to "transifex-automations", so updating html_title to match. This is consistent with the rest of the repository that expected the repository name to be "transifex-automations" already.
----
📚 Documentation preview 📚: https://python-docs-transifex-automation--133.org.readthedocs.build/en/133/
=> Fix html title after repository rename

sample-workflows/po-lint.yml, sample-workflows/test-build.yml, sample-workflows/transifex-pull.yml, sample-workflows/transifex-util.py
I need to work on a good transifex download workflow. Adding file for now.
What do you think about these workflows? I will write some docs for them once we settle on what the workflows are.
=> Add sample workflows

sample-workflows/transifex-pull.yml
The workflow pushes commits and then calls itself yet again, this one should just be on a schedule.
=> Remove `on: push` from TX sample

docs/index.rst, docs/workflows.rst
----
📚 Documentation preview 📚: https://python-docs-transifex-automation--131.org.readthedocs.build/en/131/workflows.html
=> Add sample workflows docs

.github/workflows/ci.yml, docs/index.rst
I think running every second day to start, and see if we have issues, then we can drop it to daily runs.
For #157
=> Increase CI freq to every second day

.github/workflows/lint.yml
Avoids triggering lint.yml on both `push` and `pull_request` events on Pull Requests.
=> Limit on.push events to main branch in lint.yml

.github/workflows/ci.yml
If the obsolete files are not removed, they might get pushed back to Transifex.
=> Remove obsolete PO files in CI before tx-pull

scripts/remove-msgid.sh
The string on Transifex: https://app.transifex.com/python-doc/python-newest/viewstrings/#en/reference--grammar/592026532
=> `remove-msgid.sh`: Exclude complete grammar msgid

sample-workflows/test-build.yml
Not filtering the output brings all files generated by from latex builder
=> Make pdf artifact return only PDF files

sample-workflows/test-build.yml
Considering that core dev no longer provides this, teams might want to build themselves.
=> Enable epub build
